# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28ca3070ead14e94a09159792936c92fb3f80a780737e498c28e3d5743d931311fc0479fde23bfa67380245a933da3dbe5c26212a7b326a1e7215495234f2e05

test:
  secret_key_base: 49a99c43a51d893f86a55ad03bff6a7a1021ea8ff47019538be3633cfaa21e5116733c4369cf7d589c7c59d353ac62e3f6aa889ab2a4d655cb6cd40358096a2e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
